#define SPEC_CASE_NAME "spec_nab_md_kernel"
#define SPEC_CASE_ID 0x5442017u
#define SPEC_REP_KIND SPEC_KIND_PAIR
#define SPEC_WORK_ITEMS SPEC_NAB_ATOMS
#define SPEC_WORK_ITERS SPEC_NAB_STEPS
#define SPEC_WORK_WIDTH SPEC_NAB_NEIGHBORS
#define SPEC_WORK_DEPTH SPEC_NAB_DEPTH
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_PAIR
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_GATHER
#define SPEC_COMPOSITION_PHASE0_ROUNDS 19
#define SPEC_COMPOSITION_PHASE1_ROUNDS 2
#define SPEC_COMPOSITION_FOOTPRINT_PHASE 0
#include "spec_representative_kernel.h"
