#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/env.sh"

if [[ ! -d "${SPEC_ROOT}/config" ]]; then
  echo "SPEC config directory not found: ${SPEC_ROOT}/config" >&2
  echo "Run spec_flow/install_spec2017.sh first." >&2
  exit 1
fi

CFG="${SPEC_ROOT}/config/c910-gcc-linux.cfg"
CFG_COPY="${SPEC_RUN_ROOT}/c910-gcc-linux.cfg"
TMP_CFG="$(mktemp "${CFG}.tmp.XXXXXX")"
TMP_COPY=""
trap 'rm -f "${TMP_CFG}" ${TMP_COPY:+"${TMP_COPY}"}' EXIT
mkdir -p "${SPEC_RUN_ROOT}/logs"

cat > "${TMP_CFG}" <<EOF
# C910 RISC-V Linux cross-compile config for SPEC CPU2017 bring-up.
# Generated by /work/spec_flow/write_config.sh.

ignore_errors          = 1
tune                   = base
label                  = ${SPEC_LABEL}
output_format          = txt,csv
teeout                 = yes
teerunout              = yes
makeflags              = -j4
reportable             = no
iterations             = 1
command_add_redirect   = yes
submit                 = ${SCRIPT_DIR}/spec_submit_wrapper.sh ${QEMU} ${SYSROOT} \$command
use_submit_for_speed   = yes

default=base:
CC                     = ${GCC_GLIBC}/bin/riscv64-unknown-linux-gnu-gcc
CXX                    = ${GCC_GLIBC}/bin/riscv64-unknown-linux-gnu-g++
FC                     = ${GCC_GLIBC}/bin/riscv64-unknown-linux-gnu-gfortran
CC_VERSION_OPTION      = --version
CXX_VERSION_OPTION     = --version
FC_VERSION_OPTION      = --version

OPTIMIZE               = ${C910_OPT} -march=${C910_MARCH} -mabi=${C910_MABI} -mtune=${C910_MTUNE}
EXTRA_CFLAGS           = -fcommon
EXTRA_CXXFLAGS         = ${CXX_EXTRA_FLAGS:-}
EXTRA_FFLAGS           =
EXTRA_LDFLAGS          =

EXTRA_PORTABILITY      = -DSPEC_LP64

500.perlbench_r,600.perlbench_s:
PORTABILITY            = -DSPEC_LINUX_AARCH64

502.gcc_r,602.gcc_s:
CPORTABILITY           = -DSPEC_LINUX -DSPEC_LP64
EXTRA_COPTIMIZE        = -fgnu89-inline

520.omnetpp_r,620.omnetpp_s:
CXXPORTABILITY         = -DSPEC_LINUX -DSPEC_LP64
EXTRA_CXXFLAGS         = -std=gnu++03

523.xalancbmk_r,623.xalancbmk_s:
PORTABILITY            = -DSPEC_LINUX

510.parest_r:
CXXPORTABILITY         = -DSPEC_LINUX -DSPEC_LP64
EXTRA_CXXFLAGS         = -std=gnu++03 -fpermissive

521.wrf_r,621.wrf_s:
CPORTABILITY           = -DSPEC_CASE_FLAG
FPORTABILITY           = -fconvert=big-endian
EXTRA_FFLAGS           = -fallow-argument-mismatch

526.blender_r:
PORTABILITY            = -funsigned-char -DSPEC_LINUX

527.cam4_r,627.cam4_s:
PORTABILITY            = -DSPEC_CASE_FLAG
EXTRA_COPTIMIZE        = -std=gnu89 -Wno-implicit-int
EXTRA_FFLAGS           = -fallow-argument-mismatch

628.pop2_s:
CPORTABILITY           = -DSPEC_CASE_FLAG
FPORTABILITY           = -fconvert=big-endian
EXTRA_FFLAGS           = -fallow-argument-mismatch
EOF

if [[ -f "${CFG}" ]] && cmp -s "${TMP_CFG}" "${CFG}"; then
  rm -f "${TMP_CFG}"
  echo "[config] unchanged ${CFG}"
else
  mv "${TMP_CFG}" "${CFG}"
  echo "[config] wrote ${CFG}"
fi

if [[ ! -f "${CFG_COPY}" ]] || ! cmp -s "${CFG}" "${CFG_COPY}"; then
  TMP_COPY="$(mktemp "${CFG_COPY}.tmp.XXXXXX")"
  cp "${CFG}" "${TMP_COPY}"
  mv "${TMP_COPY}" "${CFG_COPY}"
fi
chmod a+rw "${CFG}" "${CFG_COPY}" 2>/dev/null || true
