#ifndef SPEC_SPEED_REPRESENTATIVE_CASE_H
#define SPEC_SPEED_REPRESENTATIVE_CASE_H

/* Independent SPECspeed proxy configurations.  Every selector produces a
 * distinct ELF and embeds only that benchmark's SimPoint-derived phase mix. */
#if defined(SPEC_SPEED_CASE_600)
#define SPEC_CASE_NAME "spec_600_perlbench_speed_kernel"
#define SPEC_CASE_ID 0x6002017u
#define SPEC_REP_KIND SPEC_KIND_PARSER
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_PARSER
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COMPILER
#define SPEC_COMPOSITION_PHASE0_ROUNDS 14
#define SPEC_COMPOSITION_PHASE1_ROUNDS 15
#elif defined(SPEC_SPEED_CASE_602)
#define SPEC_CASE_NAME "spec_602_gcc_speed_kernel"
#define SPEC_CASE_ID 0x6022017u
#define SPEC_REP_KIND SPEC_KIND_COMPILER
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COMPILER
#define SPEC_COMPOSITION_PHASE0_ROUNDS 11
#define SPEC_COMPOSITION_PHASE1_ROUNDS 7
#elif defined(SPEC_SPEED_CASE_603)
#define SPEC_CASE_NAME "spec_603_bwaves_speed_kernel"
#define SPEC_CASE_ID 0x6032017u
#define SPEC_REP_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_PHASE0_ROUNDS 28
#define SPEC_COMPOSITION_PHASE1_ROUNDS 3
#elif defined(SPEC_SPEED_CASE_607)
#define SPEC_CASE_NAME "spec_607_cactubssn_speed_kernel"
#define SPEC_CASE_ID 0x6072017u
#define SPEC_REP_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_GROUPS 3
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COLUMN
#define SPEC_COMPOSITION_PHASE2_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_PHASE0_ROUNDS 17
#define SPEC_COMPOSITION_PHASE1_ROUNDS 9
#define SPEC_COMPOSITION_PHASE2_ROUNDS 39
#elif defined(SPEC_SPEED_CASE_619)
#define SPEC_CASE_NAME "spec_619_lbm_speed_kernel"
#define SPEC_CASE_ID 0x6192017u
#define SPEC_REP_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_PHASE0_ROUNDS 20
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_TINY_RUNTIME
#define SPEC_COMPOSITION_PHASE1_ROUNDS 8
#elif defined(SPEC_SPEED_CASE_620)
#define SPEC_CASE_NAME "spec_620_omnetpp_speed_kernel"
#define SPEC_CASE_ID 0x6202017u
#define SPEC_REP_KIND SPEC_KIND_EVENT
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_EVENT
#define SPEC_COMPOSITION_PHASE0_ROUNDS 20
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_TINY_RUNTIME
#define SPEC_COMPOSITION_PHASE1_ROUNDS 16
#elif defined(SPEC_SPEED_CASE_621)
#define SPEC_CASE_NAME "spec_621_wrf_speed_kernel"
#define SPEC_CASE_ID 0x6212017u
#define SPEC_REP_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_GROUPS 3
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_IMAGE
#define SPEC_COMPOSITION_PHASE2_KIND SPEC_KIND_COLUMN
#define SPEC_COMPOSITION_PHASE0_ROUNDS 17
#define SPEC_COMPOSITION_PHASE1_ROUNDS 5
#define SPEC_COMPOSITION_PHASE2_ROUNDS 2
#elif defined(SPEC_SPEED_CASE_623)
#define SPEC_CASE_NAME "spec_623_xalancbmk_speed_kernel"
#define SPEC_CASE_ID 0x6232017u
#define SPEC_REP_KIND SPEC_KIND_XML
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_XML
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COMPILER
#define SPEC_COMPOSITION_PHASE0_ROUNDS 25
#define SPEC_COMPOSITION_PHASE1_ROUNDS 3
#elif defined(SPEC_SPEED_CASE_625)
#define SPEC_CASE_NAME "spec_625_x264_speed_kernel"
#define SPEC_CASE_ID 0x6252017u
#define SPEC_REP_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_IMAGE
#define SPEC_COMPOSITION_PHASE0_ROUNDS 35
#define SPEC_COMPOSITION_PHASE1_ROUNDS 1
#elif defined(SPEC_SPEED_CASE_627)
#define SPEC_CASE_NAME "spec_627_cam4_speed_kernel"
#define SPEC_CASE_ID 0x6272017u
#define SPEC_REP_KIND SPEC_KIND_COLUMN
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COLUMN
#define SPEC_COMPOSITION_PHASE0_ROUNDS 1
#define SPEC_COMPOSITION_PHASE1_ROUNDS 16
#elif defined(SPEC_SPEED_CASE_631)
#define SPEC_CASE_NAME "spec_631_deepsjeng_speed_kernel"
#define SPEC_CASE_ID 0x6312017u
#define SPEC_REP_KIND SPEC_KIND_PARSER
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_PARSER
#define SPEC_COMPOSITION_PHASE0_ROUNDS 4
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_TINY_RUNTIME
#define SPEC_COMPOSITION_PHASE1_ROUNDS 1
#elif defined(SPEC_SPEED_CASE_641)
#define SPEC_CASE_NAME "spec_641_leela_speed_kernel"
#define SPEC_CASE_ID 0x6412017u
#define SPEC_REP_KIND SPEC_KIND_PARSER
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_PARSER
#define SPEC_COMPOSITION_PHASE0_ROUNDS 7
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_EVENT
#define SPEC_COMPOSITION_PHASE1_ROUNDS 1
#elif defined(SPEC_SPEED_CASE_644)
#define SPEC_CASE_NAME "spec_644_nab_speed_kernel"
#define SPEC_CASE_ID 0x6442017u
#define SPEC_REP_KIND SPEC_KIND_PAIR
#define SPEC_COMPOSITION_GROUPS 3
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_GATHER
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_PAIR
#define SPEC_COMPOSITION_PHASE2_KIND SPEC_KIND_EVENT
#define SPEC_COMPOSITION_PHASE0_ROUNDS 5
#define SPEC_COMPOSITION_PHASE1_ROUNDS 41
#define SPEC_COMPOSITION_PHASE2_ROUNDS 7
#elif defined(SPEC_SPEED_CASE_648)
#define SPEC_CASE_NAME "spec_648_exchange2_speed_kernel"
#define SPEC_CASE_ID 0x6482017u
#define SPEC_REP_KIND SPEC_KIND_PARSER
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_PARSER
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_PHASE0_ROUNDS 5
#define SPEC_COMPOSITION_PHASE1_ROUNDS 3
#elif defined(SPEC_SPEED_CASE_649)
#define SPEC_CASE_NAME "spec_649_fotonik3d_speed_kernel"
#define SPEC_CASE_ID 0x6492017u
#define SPEC_REP_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_GROUPS 3
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COLUMN
#define SPEC_COMPOSITION_PHASE2_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_PHASE0_ROUNDS 4
#define SPEC_COMPOSITION_PHASE1_ROUNDS 3
#define SPEC_COMPOSITION_PHASE2_ROUNDS 73
#elif defined(SPEC_SPEED_CASE_654)
#define SPEC_CASE_NAME "spec_654_roms_speed_kernel"
#define SPEC_CASE_ID 0x6542017u
#define SPEC_REP_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_GROUPS 3
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COLUMN
#define SPEC_COMPOSITION_PHASE2_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_PHASE0_ROUNDS 9
#define SPEC_COMPOSITION_PHASE1_ROUNDS 1
#define SPEC_COMPOSITION_PHASE2_ROUNDS 23
#elif defined(SPEC_SPEED_CASE_657)
#define SPEC_CASE_NAME "spec_657_xz_speed_kernel"
#define SPEC_CASE_ID 0x6572017u
#define SPEC_REP_KIND SPEC_KIND_COMPILER
#define SPEC_COMPOSITION_GROUPS 3
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_COMPILER
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_REDUCTION
#define SPEC_COMPOSITION_PHASE2_KIND SPEC_KIND_GATHER
#define SPEC_COMPOSITION_PHASE0_ROUNDS 20
#define SPEC_COMPOSITION_PHASE1_ROUNDS 9
#define SPEC_COMPOSITION_PHASE2_ROUNDS 5
#else
#error "one SPEC_SPEED_CASE selector is required"
#endif

#define SPEC_WORK_ITEMS 64
#define SPEC_WORK_ITERS 1
#define SPEC_WORK_WIDTH 6
#define SPEC_WORK_DEPTH 3
#define SPEC_COMPOSITION_FOOTPRINT_PHASE 0
#include "spec_representative_kernel.h"

#endif
