#define SPEC_CASE_NAME "spec_xalancbmk_xml_kernel"
#define SPEC_CASE_ID 0x5232017u
#define SPEC_REP_KIND SPEC_KIND_XML
#define SPEC_WORK_ITEMS SPEC_XALAN_NODES
#define SPEC_WORK_ITERS SPEC_XALAN_ITERS
#define SPEC_WORK_WIDTH SPEC_XALAN_ROOTS
#define SPEC_WORK_DEPTH SPEC_XALAN_DEPTH
#define SPEC_COMPOSITION_GROUPS 2
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_XML
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COMPILER
#define SPEC_COMPOSITION_PHASE0_ROUNDS 31
#define SPEC_COMPOSITION_PHASE1_ROUNDS 4
#define SPEC_COMPOSITION_FOOTPRINT_PHASE 0
#include "spec_representative_kernel.h"
