#define SPEC_CASE_NAME "spec_cam4_climate_kernel"
#define SPEC_CASE_ID 0x5272017u
#define SPEC_REP_KIND SPEC_KIND_COLUMN
#define SPEC_WORK_ITEMS SPEC_CAM4_LEVELS
#define SPEC_WORK_ITERS SPEC_CAM4_STEPS
#define SPEC_WORK_WIDTH SPEC_CAM4_COLUMNS
#define SPEC_WORK_DEPTH SPEC_CAM4_DEPTH
#define SPEC_COMPOSITION_GROUPS 3
#define SPEC_COMPOSITION_PHASE0_KIND SPEC_KIND_STENCIL
#define SPEC_COMPOSITION_PHASE1_KIND SPEC_KIND_COLUMN
#define SPEC_COMPOSITION_PHASE2_KIND SPEC_KIND_IMAGE
#define SPEC_COMPOSITION_PHASE0_ROUNDS 5
#define SPEC_COMPOSITION_PHASE1_ROUNDS 15
#define SPEC_COMPOSITION_PHASE2_ROUNDS 24
#define SPEC_COMPOSITION_PHASE0_EXTRA_ROUNDS ((SPEC_COMPOSITION_SCALE > 1) ? -1 : 0)
#define SPEC_COMPOSITION_PHASE2_EXTRA_ROUNDS ((SPEC_COMPOSITION_SCALE > 1) ? -1 : 0)
#define SPEC_COMPOSITION_FOOTPRINT_PHASE 1
#include "spec_representative_kernel.h"
